# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Простой CSS
description: > # this means to ignore newlines until "baseurl:"
  Простые правила написания CSS
baseurl: '/easy-css' # the subpath of your site, e.g. /blog

# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yoksel
github_username:  yoksel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /title/

menu:
 - name: 'Введение'
   url: '/'
 - name: 'Стиль кода'
   url: '/codestyle/'
 - name: 'Селекторы'
   url: '/selectors/'
 - name: 'Препроцессоры'
   url: '/preprocessors/'
 - name: 'Кастомные шрифты'
   url: '/custom-fonts/'
 - name: 'Инструменты'
   url: '/tools/'
 - name: 'Короткая запись свойств'
   url: '/shorthand-properties/'

socials:
 - name: '@yoksel'
   url: 'https://twitter.com/yoksel'
 - name: 'Проект на GitHub'
   url: 'https://github.com/yoksel/easy-css/'
